@startuml P2P Bank
class Main {
    + Main()
    + {static} void main(String[] args)
    + void run()
}

class Bank {
    + Bank()
    + void register(String accountId, RemoteBank bank)
    + void deposit(String accountId, int amount)
    + void withdraw(String accountId, int amount)
    + void transfer(String sourceId, String destId, int amount)
    + int getBalance(String accountId)
    + void run()
}

class RemoteBank {
    + RemoteBank(String hostname, int port, Bank bank)
    + RemoteBank(java.net.Socket, Bank bank)
    + void deposit(String accountId, int amount)
    + void withdraw(String accountId, int amount)
    + int getBalance(String accountId)
}

class Account {
    - String accountId
    - int balance
    + Account()
    + void deposit(int amount)
    + void withdraw(int amount)
    + String getAccountId()
    + int getBalance()
}

class Snapshot {
}

interface java.lang.Runnable
interface Algorithm

Main --* "1" Bank : - bank
Main ..|> java.lang.Runnable

Bank --* "1" java.net.ServerSocket : - serverSocket
Bank --* "0..*" Account : - localAccounts
Bank "[String accountId]" --* "1..*" RemoteBank : - remoteAccounts
Bank ..|> java.lang.Runnable

RemoteBank --* "1" java.net.Socket : - socket
RemoteBank --* "1" Bank : - bank
RemoteBank --* "1" java.io.BufferedReader : - in
RemoteBank --* "1" java.io.BufferedWriter : - out
RemoteBank ..|> java.lang.Runnable

@enduml